### ISSUE TITLE
Cam to give What race 0-5 means

### ISSUE THREAD

**Issue by karikashah** [Wired361/Digital-Humanities#14]

**Comment by karikashah** [comment]
Please Contact Dr. Reidel & give us the meaning of the numbers from 0- 5 for race

**Comment by CamKirk** [comment]
0 - no person
1 - person marked as “colored” in City Directory
2 - person not marked as “colored” in City Directory
3 - business marked as “colored” in City Directory
4 - business not marked as “colored” in City Directory
