### ISSUE TITLE
App.py/JS requirements

### ISSUE THREAD

**Issue by Wired361** [Wired361/Digital-Humanities#36]
## What Justin needs from you:

* Data needed for each model
* Data format to run each model
* Format of data returned from model
* Is it clean or do I need to clean it on the server

## Why is this important?

I’m rewriting Nai-Fan’s code, it’s much simpler than trying to incorporate it into a new database. I also want to merge the records from a relational table format to a mongoesque document format. *However*, I can’t do that yet because the data doesn’t have a way to join it. That’s what Dr. Riedel is doing after this project. In order to limit our interference long term, I will have the documents update and move information as he muddles through it. That way when he finishes, the data is in a nice clean format with all the information joined together in a single record, no joins required to view each individual across the current tables. *Data that is queried together should live together*.

The DB can be queried in JavaScript but no cleaning will take place after it reaches the browser. I want the data clean in the Database so if Dr. Riedel choses to move or access that data directly, no additional cleaning is required before he can use or distribute the data. 

Because of this, the data will be cleaned in python before it reaches the db. However, the data format for the models is different as they are unique to this interface/views and won’t be reused and doesn’t need to be formatted in the db. This translates to only needing a standard query/handler for __new__ data to be processed by the model and I need to know what data format you want for that.

**Comment by karikashah** [comment]
As we discussed part of the cleaning is done in python & rest can be done at JS end. We also discussed the data format for ML models.
