### ISSUE TITLE
New routes

### ISSUE THREAD

**Issue by Wired361** [Wired361/Digital-Humanities#37]
### Required Python routes:

All GET/POST/DELETE is handled by cosmos api and will be queried in JavaScript to limited server latency between front and back end, so no api routes are required for the views. 

* View 1 - Riedel Cleaning:  feed ML into template with flask

?: should data be run through the model in route function or called from separate function?

* View 2 - Map and data overview: because the data is queried in javascript, do I need anything from flask at all here? 

Would it be better to handle GET in JS and POST/DELETE in python?

**Comment by karikashah** [comment]
Restructured the cosmos api, created cosmosroutes in flask for javascript to make call for GET/POST request.
