### ISSUE TITLE
Heatmap creation with Cam

### ISSUE THREAD

**Issue by karikashah** [Wired361/Digital-Humanities#6]
Find a better way to show density
Current issue:
All years show pretty much the same data, only differences are the names, so we have to tie that in somehow

**Comment by karikashah** [comment]
Find a better way to show density
Current issue:
All years show pretty much the same data, only differences are the names, so we have to tie that in somehow

**Comment by Wired361** [comment]
Heat map created, can support new data as soon as it's available, see issue #21 for details
